Service:
  RegionId: cn-hangzhou
  DeployType: ros
  OperationMetadata:
    StatusOperationConfigs:
    - TemplateName: ECS单机版
      SupportOperations:
      - Start
      - Stop
      - Restart
    SupportBackup: true
    ModifyParametersConfig:
    - TemplateName: ECS单机版
      Operation:
      - Name: 变更ECS实例规格
        Description: 变更ECS实例规格
        Type: Custom
        Parameters:
        - EcsInstanceType
      - Name: 变更ECS实例密码
        Description: 变更ECS实例密码
        Type: Custom
        Parameters:
        - InstancePassword
  UpgradeMetadata:
    Description: 升级
    SupportUpgradeFromVersions: []
    SupportRollback: true
    UpgradeComponents:
    - Configuration
    - Resource
  DeployMetadata:
    SupplierDeployMetadata:
      SupplierTemplateConfigs:
      - Name: ECS单机版
        Url: 'ros_templates/template.yaml'
        ArchitectureDiagramUrl: 'resources/architecture/architecture.jpg'
        AllowedRegions:
        - ap-southeast-1
      ArtifactRelation:
        ecs_image_quickstart-maxkb:
          ArtifactId: ${Artifact.EcsImage.ArtifactId}
          ArtifactVersion: draft
    TemplateConfigs:
    - Name: ECS单机版
      Url: 'ros_templates/template.yaml'
      ArchitectureDiagramUrl: 'resources/architecture/architecture.jpg'
      AllowedRegions:
      - ap-southeast-1
  ServiceType: private
  ServiceInfo:
    # 英文版可以再配置Locale为en-US的服务信息
  - Locale: zh-CN
    Name: MaxKB
    ShortDescription: MaxKB = Max Knowledge Base，是一款基于 LLM 大语言模型的开源知识库问答系统，旨在成为企业的最强大脑。
    Image: 
      https://service-info-public.oss-cn-hangzhou.aliyuncs.com/1563457855438522/service-image/40274a57-6c57-4973-be2f-15be008f169a.jpg
    Softwares: []
  - Locale: en-US
    Name: MaxKB CE
    ShortDescription: MaxKB = Max Knowledge Base is an open source knowledge base
      question-answering system based on the LLM large language model, aiming to become
      the most powerful
    Image: 
      https://service-info-public.oss-cn-hangzhou.aliyuncs.com/1563457855438522/service-image/40274a57-6c57-4973-be2f-15be008f169a.jpg
    Softwares: []
Artifact:
  EcsImage:
    ArtifactType: EcsImage
    ArtifactName: ecs_image_quickstart-maxkb
    Description: quickstart-maxkb EcsImage
    SupportRegionIds:
    - ap-southeast-1
    ArtifactBuildProperty:
      CodeRepo:
        Platform: github
        Owner: KunSir991
        RepoName: aliyun-computenest/quickstart-maxkb
        Branch: main
      RegionId: ap-southeast-1
      CommandType: RunShellScript
      CommandContent: |-
        mkdir -p /root/application
        mkdir -p "/root/application/maxkb"
        if [ -e "/root/code/maxkb/.env" ]; then cp -r "/root/code/maxkb/.env" "/root/application/maxkb/"; fi
        if [ -e "/root/code/maxkb/docker-compose.yml" ]; then cp -r "/root/code/maxkb/docker-compose.yml" "/root/application/maxkb/"; fi
        mkdir -p "/root/application/maxkb/${HOME}"
        if [ -e "/root/code/maxkb/${HOME}/.maxkb" ]; then cp -r "/root/code/maxkb/${HOME}/.maxkb" "/root/application/maxkb/${HOME}/"; fi
        cd /root/application
        sed -i 's/pull_policy: always/pull_policy: if_not_present/g' maxkb/docker-compose.yml
        docker compose -f maxkb/docker-compose.yml build 
        docker compose -f maxkb/docker-compose.yml pull 2>&1 | stdbuf -oL grep -viE 'Downloading|sha256|extracting|KiB|Downloaded' || true;
